### PR TITLE
Corrected variable name in givenTheCurrentTimeIs to address error in v1.0

### PR DESCRIPTION
**Pull request by warslett**
See https://github.com/silverstripe/silverstripe-behat-extension/issues/133

### CODE REVIEW

**Comment by dhensby** [comment]
thanks

**Comment by warslett** [comment]
cheers @dhensby. Have you tagged it?

**Comment by dhensby** [comment]
No, not yet - would that help you out?

**Comment by warslett** [comment]
Yes tagging the bug fixes on 1.0 would be useful. We have been requiring this module in composer.json using `"silverstripe/behat-extension": "^1",` but the last tag on version 1 is 1.0.2 which means we don't get any bug fixes merged since then and neither will anyone else who is requiring version 1 in their projects. We get around it by requiring `"silverstripe/behat-extension": "1.0.x-dev"` which gets us all commits on the branch but that's not how most people will be requiring the package.

**Comment by dhensby** [comment]
@warslett understood.

Now tagged as 1.0.3

**Pull request merged**
