### PR TITLE
API Update to use new facebook driver extension

### PR DESCRIPTION
**Pull request by tractorcow**
Parent story https://github.com/silverstripe/silverstripe-behat-extension/issues/137

Note, after merging, create new 4 branch for this work, re-alias master as 5.x, and reset 3 branch to just before this change.

It is a breaking change, but one we want to support for framework 4.x, and not require framework 5.x.

### CODE REVIEW

**Comment by dhensby** [comment]
> Note, after merging, create new 4 branch for this work, re-alias master as 5.x, and reset 3 branch to just before this change.

Why not do this before merging :P

**Comment by tractorcow** [comment]
> Why not do this before merging :P


Because someone might say "no we don't want to merge this at all" :P

**Comment by dhensby** [comment]
I approve overall approach 🎉

**Comment by tractorcow** [comment]
Disclosure here, I'd already tagged 4.0.0-alpha1 as framework 5.x.

**Pull request merged**
